posteo.de: add new TLDs, add more mail servers,
thunderbird/autoconfig pull request #89
Opened 2024-01-15 05:38 UTC by Djfe

as requested in #83, I opened independent PRs for these commits.

2024-02-22 18:01 UTC, cketti requested changes
The domains and server settings check out :+1:

2024-02-22 18:01 UTC, cketti commented on ispdb/posteo.de.xml
> +  </webMail>
Please remove the `webMail` element (see #96).

2024-02-22 23:48 UTC, Djfe commented
Thanks for reviewing my PRs :)

2024-02-23 14:53 UTC, cketti approved these changes

2024-02-23 14:53 UTC, merged

2024-02-23 14:53 UTC, cketti commented
Thanks 👍