gmx.net: add webMail, enable, documentation, more TLDs
thunderbird/autoconfig pull request #91
Opened 2024-01-15 05:38 UTC by Djfe

as requested in #83, I opened independent PRs for these commits.
The only thing I had to adjust was the position of the enable element (See https://github.com/thunderbird/autoconfig/pull/84#issuecomment-1874793801 if you want to know why)

2024-02-22 17:36 UTC, cketti requested changes
I verified that the additional domains belong to GMX and that the `documentation` and `enable` URLs point to appropriate help pages. Thanks :+1:

This is good to go once the `webMail` element is removed.

2024-02-22 17:36 UTC, cketti commented on ispdb/gmx.net.xml
> +  </webMail>
We want to get rid of the `webMail` element (see #96). While we're not removing existing elements right away, we don't want to add new ones either.

2024-02-22 23:43 UTC, Djfe commented on ispdb/gmx.net.xml
> +  </webMail>
I addressed your suggestion. The other PRs will follow suit.

2024-02-23 14:54 UTC, cketti approved these changes

2024-02-23 14:54 UTC, merged

2024-02-23 14:54 UTC, cketti commented
Thanks 👍